name: rayspeaki
description: RaySpeaki 语音聊天客户端
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  socket_io_client: ^2.0.3+1
  http: ^1.2.1
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  image_picker: ^1.0.7
  flutter_webrtc: ^1.3.0
  mediasfu_mediasoup_client:
    path: packages/mediasfu_mediasoup_client
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
